// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_image_create(ui_Screen6);
    lv_image_set_src(ui_Image17, &ui_img_1089350595);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1549
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 909
    lv_obj_set_x(ui_Image17, -150);
    lv_obj_set_y(ui_Image17, -100);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image17, 200);

    ui_Button12 = lv_button_create(ui_Image17);
    lv_obj_set_width(ui_Button12, 152);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, -161);
    lv_obj_set_y(ui_Button12, 306);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x79830F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "返回");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_image_create(ui_Screen6);
    lv_image_set_src(ui_Image18, &ui_img_760332301);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 119
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 101
    lv_obj_set_x(ui_Image18, -363);
    lv_obj_set_y(ui_Image18, 205);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image18, 80);

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);

}
