// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image1, &ui_img_170937940);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1200
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 706
    lv_obj_set_x(ui_Image1, -4);
    lv_obj_set_y(ui_Image1, 52);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_button_create(ui_Image1);
    lv_obj_set_width(ui_Button6, 144);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, -316);
    lv_obj_set_y(ui_Button6, 156);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x3C770E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "返回");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image2, &ui_img_760332301);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 119
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 101
    lv_obj_set_x(ui_Image2, -368);
    lv_obj_set_y(ui_Image2, 207);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 80);

    ui_Image7 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image7, &ui_img_1824257103);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image7, 221);
    lv_obj_set_y(ui_Image7, 157);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 215);
    lv_obj_set_y(ui_Label13, 224);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "点击太阳花控制传感器");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xF56F0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button8, 184);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, 66);
    lv_obj_set_y(ui_Button8, 157);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xA7B42F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 1);
    lv_obj_set_y(ui_Label15, -1);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "点击自动灌溉");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image15, &ui_img_382494222);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image15, -92);
    lv_obj_set_y(ui_Image15, 134);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button10 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button10, 118);
    lv_obj_set_height(ui_Button10, 47);
    lv_obj_set_x(ui_Button10, -47);
    lv_obj_set_y(ui_Button10, -211);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 2);
    lv_obj_set_y(ui_Label41, -4);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "天气预报");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xF56F0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image7, ui_event_Image7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);

}
