// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_Screen5);
    lv_image_set_src(ui_Image14, &ui_img_1089345222);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1200
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1137
    lv_obj_set_x(ui_Image14, -3);
    lv_obj_set_y(ui_Image14, -78);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image14, 180);

    ui_Panel8 = lv_obj_create(ui_Image14);
    lv_obj_set_width(ui_Panel8, 304);
    lv_obj_set_height(ui_Panel8, 153);
    lv_obj_set_x(ui_Panel8, -171);
    lv_obj_set_y(ui_Panel8, -61);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -5);
    lv_obj_set_y(ui_Label12, -36);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "温度传感器");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch8 = lv_switch_create(ui_Panel8);
    lv_obj_set_width(ui_Switch8, 50);
    lv_obj_set_height(ui_Switch8, 25);
    lv_obj_set_x(ui_Switch8, 59);
    lv_obj_set_y(ui_Switch8, 13);
    lv_obj_set_align(ui_Switch8, LV_ALIGN_CENTER);


    ui_Label33 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 112);
    lv_obj_set_y(ui_Label33, 12);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "开");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 2);
    lv_obj_set_y(ui_Label36, 13);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "关");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 111);
    lv_obj_set_y(ui_Label30, 50);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "开");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 4);
    lv_obj_set_y(ui_Label37, 47);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "关");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch9 = lv_switch_create(ui_Panel8);
    lv_obj_set_width(ui_Switch9, 50);
    lv_obj_set_height(ui_Switch9, 25);
    lv_obj_set_x(ui_Switch9, 60);
    lv_obj_set_y(ui_Switch9, 48);
    lv_obj_set_align(ui_Switch9, LV_ALIGN_CENTER);


    ui_Label38 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -76);
    lv_obj_set_y(ui_Label38, 11);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "节点1");
    lv_obj_set_style_text_font(ui_Label38, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -75);
    lv_obj_set_y(ui_Label39, 47);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "节点2");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Image14);
    lv_obj_set_width(ui_Panel9, 279);
    lv_obj_set_height(ui_Panel9, 101);
    lv_obj_set_x(ui_Panel9, 187);
    lv_obj_set_y(ui_Panel9, 32);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -4);
    lv_obj_set_y(ui_Label26, -17);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "光照传感器");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch7 = lv_switch_create(ui_Panel9);
    lv_obj_set_width(ui_Switch7, 50);
    lv_obj_set_height(ui_Switch7, 25);
    lv_obj_set_x(ui_Switch7, 1);
    lv_obj_set_y(ui_Switch7, 25);
    lv_obj_set_align(ui_Switch7, LV_ALIGN_CENTER);


    ui_Label32 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 60);
    lv_obj_set_y(ui_Label32, 24);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "开");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -62);
    lv_obj_set_y(ui_Label35, 22);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "关");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Image14);
    lv_obj_set_width(ui_Panel10, 286);
    lv_obj_set_height(ui_Panel10, 92);
    lv_obj_set_x(ui_Panel10, 188);
    lv_obj_set_y(ui_Panel10, -86);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -2);
    lv_obj_set_y(ui_Label27, -24);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "湿度传感器");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch6 = lv_switch_create(ui_Panel10);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_x(ui_Switch6, -6);
    lv_obj_set_y(ui_Switch6, 17);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);


    ui_Label31 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 60);
    lv_obj_set_y(ui_Label31, 14);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "开");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -70);
    lv_obj_set_y(ui_Label34, 12);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "关");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Image14);
    lv_obj_set_width(ui_Panel11, 276);
    lv_obj_set_height(ui_Panel11, 103);
    lv_obj_set_x(ui_Panel11, 191);
    lv_obj_set_y(ui_Panel11, 157);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -4);
    lv_obj_set_y(ui_Label28, -21);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "病虫害监测传感器");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_Panel11);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, -10);
    lv_obj_set_y(ui_Switch5, 30);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);


    ui_Label21 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 33);
    lv_obj_set_y(ui_Label21, 26);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "开");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -65);
    lv_obj_set_y(ui_Label29, 23);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "关");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_Image14);
    lv_obj_set_width(ui_Button9, 152);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, -312);
    lv_obj_set_y(ui_Button9, 280);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x969436), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "返回");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Image14);
    lv_obj_set_width(ui_Panel13, 304);
    lv_obj_set_height(ui_Panel13, 153);
    lv_obj_set_x(ui_Panel13, -168);
    lv_obj_set_y(ui_Panel13, 135);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -5);
    lv_obj_set_y(ui_Label53, -36);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "ZIGBEE采集光照数据");
    lv_obj_set_style_text_font(ui_Label53, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -10);
    lv_obj_set_y(ui_Label50, 17);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "");
    lv_obj_set_style_text_font(ui_Label50, &ui_font_chinese28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_image_create(ui_Screen5);
    lv_image_set_src(ui_Image16, &ui_img_760332301);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 119
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 101
    lv_obj_set_x(ui_Image16, -266);
    lv_obj_set_y(ui_Image16, 203);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image16, 80);

    lv_obj_add_event_cb(ui_Switch8, ui_event_Switch8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch9, ui_event_Switch9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch7, ui_event_Switch7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch6, ui_event_Switch6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch5, ui_event_Switch5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}
