// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image4;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Label4(lv_event_t * e);
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label8;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label11;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label44;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image12;
void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart2_Xaxis;
extern lv_obj_t * ui_Chart2_Yaxis1;
extern lv_obj_t * ui_Chart2_Yaxis2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Switch4;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image1;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image2;
void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label13;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image15;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label41;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label12;
void ui_event_Switch8(lv_event_t * e);
extern lv_obj_t * ui_Switch8;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label37;
void ui_event_Switch9(lv_event_t * e);
extern lv_obj_t * ui_Switch9;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label26;
void ui_event_Switch7(lv_event_t * e);
extern lv_obj_t * ui_Switch7;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label27;
void ui_event_Switch6(lv_event_t * e);
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label28;
void ui_event_Switch5(lv_event_t * e);
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label29;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Image16;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Image17;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_login_png);    // assets/login.png
LV_IMG_DECLARE(ui_img_1491427109);    // assets/组 poto.png
LV_IMG_DECLARE(ui_img_1168434321);    // assets/组 3030.png
LV_IMG_DECLARE(ui_img_170934617);    // assets/分组 6.png
LV_IMG_DECLARE(ui_img_13_png);    // assets/13.png
LV_IMG_DECLARE(ui_img_760332301);    // assets/组 367.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_1089338824);    // assets/画板 5.png
LV_IMG_DECLARE(ui_img_777875057);    // assets/组 132.png
LV_IMG_DECLARE(ui_img_170937940);    // assets/分组 1.png
LV_IMG_DECLARE(ui_img_1824257103);    // assets/reshot-icon-field-of-sunflower-V3S9J8U7GW (1).png
LV_IMG_DECLARE(ui_img_382494222);    // assets/reshot-icon-farm-watering-system-WTRAFG3CXQ.png
LV_IMG_DECLARE(ui_img_1089345222);    // assets/画板 7.png
LV_IMG_DECLARE(ui_img_1089350595);    // assets/画板 2.png



LV_FONT_DECLARE(ui_font_chinese28);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
