// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void LOGIN_TASK(lv_event_t * e)
{
	// Your code here
}

void REGISTER_TASK(lv_event_t * e)
{
	// Your code here
}

void temp_sensor1(lv_event_t * e)
{
	// Your code here
}

void temp_sensor2(lv_event_t * e)
{
	// Your code here
}

void light_sensor(lv_event_t * e)
{
	// Your code here
}

void hum_sensor(lv_event_t * e)
{
	// Your code here
}

void press_sensor(lv_event_t * e)
{
	// Your code here
}
